// Generated by cargo run -p flightlens-core --bin bindings. Do not edit.
export type Value = { "kind": "integer", "value": number } | { "kind": "decimal", "value": number } | { "kind": "text", "value": string };

export type Scope = { "kind": "global" } | { "kind": "pid", "index": number } | { "kind": "rate", "index": number } | { "kind": "unknown" };

export type Parameter = { key: string, semanticKey: string, value: Value, rawValue: string, scope: Scope, line: number, valid: boolean, supported: boolean, unit: string | null, packId: string | null, };

export type Derived = { key: string, scope: Scope, value: Value, rawValue: string, 
/**
 * The certified firmware line whose reset table supplied the value, which
 * is what stands in for a source line in the interface.
 */
sourceVersion: string, };

export type Diagnostic = { line: number | null, severity: string, message: string, };

export type Command = { "kind": "set", key: string, value: string, } | { "kind": "profile", index: number, } | { "kind": "rateprofile", index: number, } | { "kind": "defaults" } | { "kind": "feature", name: string, enabled: boolean, } | { "kind": "serial", identifier: number, mask: number, baud: [number, number, number, number], } | { "kind": "aux", index: number, mode: number, channel: number, start: number, end: number, logic: number | null, linked: number | null, } | { "kind": "collection", name: string, operands: Array<string>, } | { "kind": "device" } | { "kind": "comment" } | { "kind": "blank" } | { "kind": "unsupported" } | { "kind": "malformed" };

export type SyntaxLine = { line: number, start: number, end: number, raw: string, command: Command, };

export type Firmware = { family: string, version: string | null, 
/**
 * The flashed target the backup names on its `board_name` line. `None`
 * when the source carries no such line, as a headerless excerpt does.
 */
boardName: string | null, header: string | null, packId: string | null, };

export type Port = { identifier: number, name: string, mask: number, functions: Array<string>, baud: [number, number, number, number], line: number, };

export type Mode = { index: number, modeId: number, name: string, channel: number, 
/**
 * Whether `channel` names one of the AUX channels Betaflight can assign.
 * The firmware prints the stored byte unclamped, so a dump can carry a
 * channel no build accepts; see `parser::AUX_CHANNEL_COUNT`.
 */
channelAssigned: boolean, start: number, end: number, logic: number | null, linked: number | null, line: number, };

export type ConfigDocument = { id: string, sourceId: string, title: string, hash: string, firmware: Firmware, 
/**
 * The craft name the backup declares, from `set craft_name` where the
 * firmware has that setting and from the `# name:` header a dump writes
 * otherwise. `None` when the backup names no craft.
 */
craftName: string | null, 
/**
 * The pilot name the backup declares. Betaflight added `pilot_name` in
 * 4.4, so a 4.2 or 4.3 dump never carries one.
 */
pilotName: string | null, completeness: string, parameters: { [key in string]?: Parameter }, 
/**
 * Keyed like `parameters`, and disjoint from it: a key any source line
 * declares is never derived, so an invalid declared value stays unknown
 * rather than being quietly replaced by the default.
 */
derived: { [key in string]?: Derived }, 
/**
 * Why nothing was read back, when the firmware is one FlightLens has a
 * reset table for but the document still does not qualify. `None` both
 * when defaults were applied and when there is no table to apply.
 */
derivedNote: string | null, syntax: Array<SyntaxLine>, diagnostics: Array<Diagnostic>, ports: Array<Port>, modes: Array<Mode>, features: { [key in string]?: boolean }, pidProfiles: Array<number>, rateProfiles: Array<number>, selectedPid: number | null, selectedRate: number | null, };

export type Artifact = { "kind": "config", "document": ConfigDocument } | { "kind": "recognized", "document": RecognizedArtifact };

export type RecognizedArtifact = { id: string, title: string, family: string, message: string, };

export type SourceDescriptor = { id: string, label: string, };

export type RestoredSession = { sources: Array<SourceDescriptor>, 
/**
 * File names the saved session listed that can no longer be opened.
 */
unavailable: Array<string>, };

export type Point = { x: number, y: number, };

export type Curve = { name: string, points: Array<Point>, reason: string | null, 
/**
 * Inputs this curve read back from the firmware's reset table because the
 * source omits them, in the order the rate law consumes them. Empty when
 * every input is declared.
 */
derivedInputs: Array<string>, };

export type OsdElement = { key: string, packed: number, x: number, y: number, visibleProfiles: number, displayType: number, line: number, preview: string, };

export type RuleEvaluation = { id: string, status: string, severity: string, explanation: string, lines: Array<number>, reference: string, };

export type Inspection = { rates: Array<Curve>, osd: Array<OsdElement>, audits: Array<RuleEvaluation>, };

export type ExportRequest = { groups: Array<string>, pidProfile: number, rateProfile: number, destinationHeader: string, includeSave: boolean, };

export type ValidatedSnippet = { text: string, warnings: Array<string>, additions: Array<string>, };

export type Category = "identity" | "link_secret";

export type Redaction = { 
/**
 * The setting whose value was removed, or `name` for the dump header.
 */
key: string, line: number, category: Category, };

export type ReportKind = "bug" | "feature";

export type FeedbackRequest = { kind: ReportKind, subject: string, body: string, 
/**
 * Whether the reporter chose to attach the open backup. Attaching is
 * always the reporter's decision, never a default.
 */
includeConfig: boolean, 
/**
 * The running FlightLens version and host platform. The core cannot
 * observe either, so the shell supplies both.
 */
appVersion: string, platform: string, };

export type FeedbackReport = { 
/**
 * The prefilled issue URL to open in the reporter's browser.
 */
url: string, 
/**
 * The issue body as it will arrive prefilled, so the dialog can show what
 * the browser is about to be handed.
 */
issueBody: string, 
/**
 * The redacted backup to place on the clipboard, and the same text the
 * dialog shows for review. `None` when no configuration was attached.
 */
clipboard: string | null, 
/**
 * Every value redaction removed, so the reporter sees what is missing
 * from what they are about to publish.
 */
removed: Array<Redaction>, 
/**
 * Whether the redacted backup is too large to paste into an issue body.
 */
oversized: boolean, };
