// Generated by cargo run -p flightlens-core --bin bindings. Do not edit.
export type Value = { "kind": "integer", "value": number } | { "kind": "decimal", "value": number } | { "kind": "text", "value": string };

export type Scope = { "kind": "global" } | { "kind": "pid", "index": number } | { "kind": "rate", "index": number } | { "kind": "unknown" };

export type Parameter = { key: string, semanticKey: string, value: Value, rawValue: string, scope: Scope, line: number, valid: boolean, supported: boolean, unit: string | null, packId: string | null, };

export type Diagnostic = { line: number | null, severity: string, message: string, };

export type Command = { "kind": "set", key: string, value: string, } | { "kind": "profile", index: number, } | { "kind": "rateprofile", index: number, } | { "kind": "defaults" } | { "kind": "feature", name: string, enabled: boolean, } | { "kind": "serial", identifier: number, mask: number, baud: [number, number, number, number], } | { "kind": "aux", index: number, mode: number, channel: number, start: number, end: number, logic: number | null, linked: number | null, } | { "kind": "collection", name: string, operands: Array<string>, } | { "kind": "device" } | { "kind": "comment" } | { "kind": "blank" } | { "kind": "unsupported" } | { "kind": "malformed" };

export type SyntaxLine = { line: number, start: number, end: number, raw: string, command: Command, };

export type Firmware = { family: string, version: string | null, header: string | null, packId: string | null, };

export type Port = { identifier: number, name: string, mask: number, functions: Array<string>, baud: [number, number, number, number], line: number, };

export type Mode = { index: number, modeId: number, name: string, channel: number, start: number, end: number, logic: number | null, linked: number | null, line: number, };

export type ConfigDocument = { id: string, sourceId: string, title: string, hash: string, firmware: Firmware, completeness: string, parameters: { [key in string]?: Parameter }, syntax: Array<SyntaxLine>, diagnostics: Array<Diagnostic>, ports: Array<Port>, modes: Array<Mode>, features: { [key in string]?: boolean }, pidProfiles: Array<number>, rateProfiles: Array<number>, selectedPid: number | null, selectedRate: number | null, };

export type Artifact = { "kind": "config", "document": ConfigDocument } | { "kind": "recognized", "document": RecognizedArtifact };

export type RecognizedArtifact = { id: string, title: string, family: string, message: string, };

export type SourceDescriptor = { id: string, label: string, };

export type Point = { x: number, y: number, };

export type Curve = { name: string, points: Array<Point>, reason: string | null, };

export type OsdElement = { key: string, packed: number, x: number, y: number, visibleProfiles: number, displayType: number, line: number, preview: string, };

export type RuleEvaluation = { id: string, status: string, severity: string, explanation: string, lines: Array<number>, reference: string, };

export type Inspection = { rates: Array<Curve>, osd: Array<OsdElement>, audits: Array<RuleEvaluation>, };

export type ExportRequest = { groups: Array<string>, pidProfile: number, rateProfile: number, destinationHeader: string, includeSave: boolean, };

export type ValidatedSnippet = { text: string, warnings: Array<string>, additions: Array<string>, };
