import type { LlmSettings, LlmStatus, Provider } from "./bindings/core";

export const providers: Record<Provider, string> = {
  gemini: "Gemini",
  openai: "OpenAI",
  openrouter: "OpenRouter",
  custom: "Custom / local model",
};
export function providerSettings(provider: Provider): LlmSettings {
  return {
    enabled: false,
    provider,
    model: {
      gemini: "gemini-3.8-flash",
      openai: "gpt-4.1-mini",
      openrouter: "openai/gpt-4.1-mini",
      custom: "",
    }[provider],
    baseUrl: provider === "custom" ? "http://localhost:11434" : null,
    timeoutSeconds: 60,
  };
}
export function settingsProblem(settings: LlmSettings): string {
  if (
    !settings.model ||
    settings.model.length > 200 ||
    !(settings.provider === "gemini" ? /^[\w.-]+$/ : /^[\w./:-]+$/).test(
      settings.model,
    ) ||
    settings.model.split("/").some((part) => ["", ".", ".."].includes(part))
  )
    return "Enter a valid model ID.";
  if (
    !Number.isInteger(settings.timeoutSeconds) ||
    settings.timeoutSeconds < 5 ||
    settings.timeoutSeconds > 180
  )
    return "Timeout must be between 5 and 180 seconds.";
  if (settings.provider === "custom") {
    const value = settings.baseUrl ?? "";
    try {
      const url = new URL(value);
      const local =
        url.hostname === "localhost" ||
        url.hostname === "[::1]" ||
        /^127\.\d+\.\d+\.\d+$/.test(url.hostname);
      if (
        !/^https?:\/\//.test(value) ||
        /[^\x21-\x7e]|[%\\?#@]/.test(value) ||
        (url.protocol !== "https:" && !(url.protocol === "http:" && local))
      )
        return "Use HTTPS, or HTTP for a loopback model endpoint, without credentials, query or fragment.";
    } catch {
      return "Enter a valid base URL.";
    }
  }
  return "";
}
export function summaryProblem(
  desktop: boolean,
  status: LlmStatus | null,
): string {
  if (!desktop) return "AI summaries require the desktop app.";
  if (!status) return "AI settings are unavailable.";
  if (!status.settings.enabled)
    return "AI summaries are off. Enable them in settings.";
  if (!status.hasKey && status.settings.provider !== "custom")
    return "Add an API key in settings.";
  return "";
}
export const disclaimer =
  "This text was generated by an external language model from a redacted summary of the backup. It is not produced or verified by FlightLens, and it is not a certified finding. Check every claim against the Inspector, Compare and Raw views before acting on it.";
export const generatedTime = (value: string) =>
  new Date(Number(value) * 1000).toLocaleString();
